hasKey = false;//do not use
hasCash = false;//do not use
hasInfluencedGuard = false; //do not use
isSearchingForCash = false;//do not use
hasReceivedKeyLocation = false;//do not use
isTalkingToGuard = false;
isTalkingToPrisoner = false;
hasStone = false;
hasChisel = false;
hasGuardDistracted = true;
hasChiselLocation = true;
hasStoneLocation = true;
isInspecting = false;
hasTalkedToPrisoner = true;
hasWon = false;

hsp = 0;
vsp = 0; 
moveSpeed = 4; 
